import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  globalIgnores(['dist']),
  {
    files: ['**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
  },
  {
    // shadcn/ui components are vendor-generated (CLI-managed) and intentionally
    // export a component alongside its `*Variants` cva object. That dual export
    // trips react-refresh/only-export-components — a known shadcn false positive.
    // We must not hand-edit these files (a future `shadcn add` would wipe it),
    // so the rule is scoped off here instead.
    files: ['src/components/ui/**'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    // Auto-generated design-system entry for the claude.ai/design sync (see
    // .ds-entry.tsx's own header comment and .design-sync/). It's a barrel of
    // `export *` re-exports, which the rule can never statically verify only
    // exports components, and it isn't imported by the app itself — so Fast
    // Refresh reliability there doesn't matter. Regenerated by tooling, so
    // this must live in config rather than a file-local disable comment.
    files: ['.ds-entry.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
])
