-- Real estate: full property description, automatic valuation from open data,
-- and per-member ownership shares.
--
-- Numbered V66 rather than V64: the crypto exchange branch already owns V64/V65.
-- flyway.out-of-order is enabled precisely because branches number independently,
-- so skipping ahead avoids a filename collision when that branch merges.

-- ─── 1. real_estate_metadata: Finary-parity property description ─────────────
--
-- purchase_price (V19) stays "hors frais" -- the acquisition fees below are kept
-- separate so the cost basis can be shown both ways.

ALTER TABLE real_estate_metadata
    -- Classification
    ADD COLUMN category          VARCHAR(30),
    ADD COLUMN description       TEXT,

    -- Address & geocoding (filled by the Geoplateforme adapter)
    ADD COLUMN postal_code       VARCHAR(10),
    ADD COLUMN city              VARCHAR(120),
    ADD COLUMN country           VARCHAR(2)   NOT NULL DEFAULT 'FR',
    ADD COLUMN insee_code        VARCHAR(5),
    ADD COLUMN latitude          NUMERIC(9, 6),
    ADD COLUMN longitude         NUMERIC(9, 6),
    ADD COLUMN ban_id            VARCHAR(60),
    ADD COLUMN parcel_id         VARCHAR(20),
    ADD COLUMN geocode_score     NUMERIC(4, 3),
    ADD COLUMN geocoded_at       TIMESTAMPTZ,

    -- Physical characteristics
    ADD COLUMN land_area         NUMERIC(10, 2),
    ADD COLUMN construction_year SMALLINT,
    ADD COLUMN rooms             SMALLINT,
    ADD COLUMN bedrooms          SMALLINT,
    -- floor_number, not "floor": unambiguous next to floors_total.
    ADD COLUMN floor_number      SMALLINT,
    ADD COLUMN floors_total      SMALLINT,
    ADD COLUMN has_elevator      BOOLEAN,
    ADD COLUMN garage_count      SMALLINT     NOT NULL DEFAULT 0,
    ADD COLUMN parking_count     SMALLINT     NOT NULL DEFAULT 0,
    ADD COLUMN has_garden        BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN has_terrace       BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN has_balcony       BOOLEAN      NOT NULL DEFAULT FALSE,
    ADD COLUMN energy_class      VARCHAR(1),

    -- Acquisition costs
    ADD COLUMN agency_fees       NUMERIC(20, 8),
    ADD COLUMN notary_fees       NUMERIC(20, 8),
    ADD COLUMN works_cost        NUMERIC(20, 8),

    -- MANUAL freezes the balance against the estimator.
    ADD COLUMN valuation_mode    VARCHAR(20)  NOT NULL DEFAULT 'ESTIMATED';

ALTER TABLE real_estate_metadata
    ADD CONSTRAINT ck_real_estate_metadata_valuation_mode
        CHECK (valuation_mode IN ('ESTIMATED', 'MANUAL')),
    ADD CONSTRAINT ck_real_estate_metadata_energy_class
        CHECK (energy_class IS NULL OR energy_class BETWEEN 'A' AND 'G'),
    ADD CONSTRAINT ck_real_estate_metadata_construction_year
        CHECK (construction_year IS NULL OR construction_year BETWEEN 1000 AND 2200);

CREATE INDEX idx_real_estate_metadata_insee ON real_estate_metadata (insee_code)
    WHERE insee_code IS NOT NULL;

-- ─── 2. property_valuation: one row per estimate ─────────────────────────────
--
-- Keeping the history (rather than a single current value) is what makes the
-- gain/loss curve and the "how was this computed" panel possible. method_detail
-- holds the applied coefficients as JSON so an estimate stays auditable after
-- the heuristics change.

CREATE TABLE property_valuation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT         NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    member_id       BIGINT         NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    valued_at       DATE           NOT NULL,
    estimated_value NUMERIC(20, 8) NOT NULL,
    low_value       NUMERIC(20, 8),
    high_value      NUMERIC(20, 8),
    price_per_sqm   NUMERIC(20, 8),
    provider        VARCHAR(30)    NOT NULL,
    confidence      VARCHAR(10),
    sample_size     INTEGER,
    source_year     SMALLINT,
    method_detail   TEXT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_property_valuation_account_date UNIQUE (account_id, valued_at),
    CONSTRAINT ck_property_valuation_confidence
        CHECK (confidence IS NULL OR confidence IN ('HIGH', 'MEDIUM', 'LOW'))
);

CREATE INDEX idx_property_valuation_account ON property_valuation (account_id);
CREATE INDEX idx_property_valuation_member  ON property_valuation (member_id);

-- ─── 3. account_ownership: per-member shares ─────────────────────────────────
--
-- Semantics, relied on throughout AccountAccessResolver:
--
--   * No row for an account  =>  its owning member holds 100%. This is the
--     default, which is why no backfill is needed: every existing account stays
--     correct without writing a single row.
--   * When rows exist, the owning member must have one (enforced in the service,
--     not here -- it needs the account's member_id, and a CHECK cannot join).
--   * SUM(share_percent) <= 100, not necessarily = 100. The remainder belongs to
--     parties outside Picsou (indivision with a non-member, an SCI...) and
--     counts towards nobody's net worth while still being part of the property's
--     gross value.
--
-- The table is keyed on account_id generally, but this iteration only applies
-- shares to REAL_ESTATE and LOAN accounts. Splitting a joint checking account
-- would also have to split its transactions, which is a separate discussion.

CREATE TABLE account_ownership (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT        NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    member_id     BIGINT        NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    share_percent NUMERIC(6, 3) NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_account_ownership_account_member UNIQUE (account_id, member_id),
    CONSTRAINT ck_account_ownership_share
        CHECK (share_percent > 0 AND share_percent <= 100)
);

CREATE INDEX idx_account_ownership_account ON account_ownership (account_id);
CREATE INDEX idx_account_ownership_member  ON account_ownership (member_id);
