-- Per-member allocation targets for the investment pyramid, and the per-ticker overrides
-- that let a holding be classified against the account it happens to sit in.
--
-- No row in member_allocation_profile means "the shipped defaults", exactly like
-- account_ownership where the absence of a row means the owner holds 100%: nothing is
-- backfilled and every existing member is correct on first start. The @Builder.Default
-- values on the entity are the source of truth; the DEFAULTs below mirror them so a direct
-- INSERT lands on the same numbers.
--
-- VARCHAR + a named CHECK rather than CREATE TYPE: the three native enums (account_type,
-- requisition_status, sharing_level) all predate V21 and nothing since has added one. It
-- also sidesteps the ALTER TYPE ... ADD VALUE transaction restriction for any future tier.

CREATE TABLE member_allocation_profile (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                  BIGINT        NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    -- NULL = never set. The UI proposes an estimate from transactions; accepting it is an
    -- explicit write, never a silent one, so NULL stays meaningful ("we do not know").
    monthly_essential_expenses NUMERIC(20, 2),
    safety_net_months          SMALLINT      NOT NULL DEFAULT 6,
    real_estate_pct            NUMERIC(5, 2) NOT NULL DEFAULT 30.00,
    equity_pct                 NUMERIC(5, 2) NOT NULL DEFAULT 50.00,
    crypto_pct                 NUMERIC(5, 2) NOT NULL DEFAULT 10.00,
    alternative_pct            NUMERIC(5, 2) NOT NULL DEFAULT 10.00,
    created_at                 TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at                 TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_member_allocation_profile_member UNIQUE (member_id),
    CONSTRAINT ck_member_allocation_profile_sum
        CHECK (real_estate_pct + equity_pct + crypto_pct + alternative_pct = 100),
    CONSTRAINT ck_member_allocation_profile_pct
        CHECK (real_estate_pct >= 0 AND equity_pct >= 0
           AND crypto_pct >= 0 AND alternative_pct >= 0),
    CONSTRAINT ck_member_allocation_profile_months
        CHECK (safety_net_months BETWEEN 1 AND 24),
    CONSTRAINT ck_member_allocation_profile_expenses
        CHECK (monthly_essential_expenses IS NULL OR monthly_essential_expenses >= 0)
);

-- Keyed on (member_id, ticker), NOT on account_holding.id and NOT as a column on
-- account_holding: the sync paths delete holding rows a provider stops reporting, so an
-- override stored there would evaporate on the first transient gap and silently take the
-- user's classification with it. Here it survives the prune, the re-sync and the account's
-- deletion, and one row covers the same gold ETC held in two accounts.
CREATE TABLE holding_classification (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT      NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    ticker      VARCHAR(30) NOT NULL,
    wealth_tier VARCHAR(20),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_holding_classification_member_ticker UNIQUE (member_id, ticker),
    CONSTRAINT ck_holding_classification_tier CHECK (wealth_tier IS NULL OR wealth_tier IN
        ('SAFETY_NET', 'REAL_ESTATE', 'EQUITY', 'CRYPTO', 'ALTERNATIVE'))
);
