-- A durable cache of what a security is, so the diversification roll-up never scrapes on the
-- read path.
--
-- Global, not member-scoped: a security's sector is nobody's private data. Same reasoning that
-- already makes price_snapshot and /api/securities/{ticker}/insight member-agnostic.
--
-- It exists because SecurityInsightService's cache is a ConcurrentHashMap that dies on restart.
-- A portfolio-wide breakdown needs one lookup per distinct ticker, so the first render after
-- every deploy would fan out N synchronous requests against an unofficial HTML page — slow, and
-- a good way to get the instance blocked. SchedulerService warms this table weekly instead.

CREATE TABLE security_profile (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker       VARCHAR(30) NOT NULL,
    asset_type   VARCHAR(20) NOT NULL,
    -- Set for a single share; an ETF carries its breakdown in the slices table instead.
    sector_key   VARCHAR(40),
    country_key  VARCHAR(2),
    source       VARCHAR(60),
    as_of        DATE,
    refreshed_at TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_security_profile_ticker UNIQUE (ticker),
    CONSTRAINT ck_security_profile_asset_type
        CHECK (asset_type IN ('ETF', 'STOCK', 'CRYPTO', 'UNKNOWN'))
);

-- One row per slice of an ETF's look-through. Relational rather than a JSON blob: the project
-- uses no JSONB anywhere, and rows can be asserted on in a @DataJpaTest.
CREATE TABLE security_composition_slice (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT        NOT NULL REFERENCES security_profile(id) ON DELETE CASCADE,
    kind       VARCHAR(10)   NOT NULL,
    label      VARCHAR(120)  NOT NULL,
    percent    NUMERIC(6, 3) NOT NULL,
    CONSTRAINT uk_security_composition_slice_profile_kind_label UNIQUE (profile_id, kind, label),
    CONSTRAINT ck_security_composition_slice_kind CHECK (kind IN ('COMPANY', 'COUNTRY', 'SECTOR'))
);

CREATE INDEX idx_security_composition_slice_profile ON security_composition_slice(profile_id);

-- The same override row that already carries a wealth tier now carries the user's verdict on
-- sector and country too. One row per (member, ticker), so correcting a misfiled holding is one
-- action whichever of the three is wrong.
ALTER TABLE holding_classification
    ADD COLUMN sector_key  VARCHAR(40),
    ADD COLUMN country_key VARCHAR(2);

ALTER TABLE holding_classification
    ADD CONSTRAINT ck_holding_classification_country
        CHECK (country_key IS NULL OR country_key ~ '^[A-Z]{2}$');
