-- Where a recurring investment plan's monthly amount actually goes.
--
-- A plan already says "400 EUR a month into the PEA". It could not say "200 into CW8 and 200
-- into ESE", which is the part a member revisits: the amount is a standing order, the split is
-- a decision. One child row per line keeps the plan itself untouched, so every existing plan
-- stays valid with no breakdown at all -- an empty set means "not detailed", never "nothing".
--
-- ticker, not an id: a line is identified the way account_holding identifies it, and the same
-- 30-character key. Holding rows are deleted and rebuilt by the sync paths (see the comment on
-- holding_classification in V83), so a foreign key to account_holding.id would evaporate on the
-- first transient gap and take the member's split with it.
--
-- The sum of a plan's rows must not exceed its monthly_amount. That is deliberately NOT a CHECK:
-- the rule spans several rows and the parent table, which a row-level constraint cannot see. It
-- lives in GoalRequest as an @AssertTrue, beside the other cross-field rules -- and a partial
-- split is legal by design, the remainder simply reads as unallocated.

CREATE TABLE goal_allocation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal_id        BIGINT        NOT NULL REFERENCES goal(id) ON DELETE CASCADE,
    ticker         VARCHAR(30)   NOT NULL,
    monthly_amount NUMERIC(20, 2) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    -- Also the index on goal_id: its leading column is the one every read filters on.
    CONSTRAINT uk_goal_allocation_goal_ticker UNIQUE (goal_id, ticker),
    CONSTRAINT ck_goal_allocation_amount CHECK (monthly_amount > 0)
);
