-- Who the member is, fiscally: the context a portfolio cannot be read without.
--
-- Picsou knows what someone owns and nothing about the person holding it. A 30 000 EUR PEA means
-- something different at 25 with a 11% marginal rate than at 58 with 41%, and the export exists
-- to be read by someone -- or something -- that needs to tell the two apart.
--
-- Separate from member_allocation_profile rather than bolted onto it. That table is replaced
-- wholesale by PUT /api/analysis/allocation-targets: adding fiscal columns to it would mean the
-- allocation modal silently wiped the profile on every save, unless a merge were added to guard
-- against it. Two tables, two endpoints, nothing to remember.
--
-- Every column is nullable, and stays so. Absence means "never stated", exactly as it does in
-- member_allocation_profile.monthly_essential_expenses -- a guessed number promoted to a stored
-- one is indistinguishable from one the member vouched for. No row at all is the same answer,
-- which is why introducing this table needs no backfill.
--
-- VARCHAR + a named CHECK rather than CREATE TYPE, for the reason given at the top of V83: the
-- three native enums all predate V21, and this sidesteps the ALTER TYPE ... ADD VALUE
-- transaction restriction for any value added later.

CREATE TABLE member_profile (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                BIGINT      NOT NULL REFERENCES family_member(id) ON DELETE CASCADE,
    -- The date, not the age: an age stored as an integer is wrong the morning after a birthday
    -- and nothing in the app would ever correct it. The API derives the age on read.
    birth_date               DATE,
    -- Percent, not a ratio, because that is how a tax bracket is named (11, 30, 41, 45).
    marginal_tax_rate        NUMERIC(5, 2),
    household_status         VARCHAR(20),
    tax_household_parts      NUMERIC(4, 2),
    dependents               SMALLINT,
    -- Gross: it is the figure a payslip states, and few people know their annual net
    -- without looking it up. Fiscal context only -- nothing is computed from it.
    annual_gross_income      NUMERIC(20, 2),
    -- The savings rate needs money that actually landed, and these two are what produce it
    -- without inventing anything. Both are printed on every French payslip: the "net a payer
    -- avant impot sur le revenu" line, and the withholding rate applied to it.
    --
    -- Gross cannot get there on its own: social contributions come first (~22-25%, varying by
    -- status) and withholding second, so deriving net from gross would mean storing a
    -- contribution rate nobody knows offhand -- a guessed figure indistinguishable from a
    -- stated one, which is what member_allocation_profile.monthly_essential_expenses refuses
    -- to become.
    monthly_net_before_tax   NUMERIC(20, 2),
    withholding_tax_rate     NUMERIC(5, 2),
    monthly_savings_capacity NUMERIC(20, 2),
    target_retirement_age    SMALLINT,
    risk_profile             VARCHAR(20),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_member_profile_member UNIQUE (member_id),
    CONSTRAINT ck_member_profile_birth_date
        CHECK (birth_date IS NULL OR birth_date > DATE '1900-01-01'),
    CONSTRAINT ck_member_profile_marginal_tax_rate
        CHECK (marginal_tax_rate IS NULL OR (marginal_tax_rate >= 0 AND marginal_tax_rate <= 100)),
    CONSTRAINT ck_member_profile_household_status
        CHECK (household_status IS NULL OR household_status IN ('SINGLE', 'COUPLE')),
    CONSTRAINT ck_member_profile_parts
        CHECK (tax_household_parts IS NULL OR (tax_household_parts >= 1 AND tax_household_parts <= 20)),
    CONSTRAINT ck_member_profile_dependents
        CHECK (dependents IS NULL OR (dependents >= 0 AND dependents <= 20)),
    CONSTRAINT ck_member_profile_annual_gross_income
        CHECK (annual_gross_income IS NULL OR annual_gross_income >= 0),
    CONSTRAINT ck_member_profile_monthly_net_before_tax
        CHECK (monthly_net_before_tax IS NULL OR monthly_net_before_tax >= 0),
    CONSTRAINT ck_member_profile_withholding_tax_rate
        CHECK (withholding_tax_rate IS NULL
               OR (withholding_tax_rate >= 0 AND withholding_tax_rate <= 100)),
    CONSTRAINT ck_member_profile_monthly_savings_capacity
        CHECK (monthly_savings_capacity IS NULL OR monthly_savings_capacity >= 0),
    CONSTRAINT ck_member_profile_retirement_age
        CHECK (target_retirement_age IS NULL OR (target_retirement_age >= 40 AND target_retirement_age <= 90)),
    CONSTRAINT ck_member_profile_risk_profile
        CHECK (risk_profile IS NULL OR risk_profile IN ('PRUDENT', 'BALANCED', 'DYNAMIC', 'AGGRESSIVE'))
);
