package com.picsou.port;

public enum AmundiErrorCode {
    INVALID_CREDENTIALS,
    CAPTCHA_BLOCKED,
    INVALID_OTP,
    APP_VALIDATION_TIMEOUT,
    AUTH_ATTEMPT_EXPIRED,
    SESSION_EXPIRED,
    PORTFOLIO_INCOMPLETE,
    UPSTREAM_FORMAT_CHANGED,
    UPSTREAM_UNAVAILABLE,
    INVALID_DATA,
    INTERNAL_ERROR
}
